"""accounting tables

Revision ID: 219e77516733
Revises: 4a296862758a
Create Date: 2026-07-18 23:30:40.378312
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '219e77516733'
down_revision: str | None = '4a296862758a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name='fk_updated_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_name'), ['name'], unique=False)

    op.create_table('journal_entries',
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name='fk_updated_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries'))
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('journal_lines',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('memo', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_journal_lines_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], name=op.f('fk_journal_lines_entry_id_journal_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name='fk_updated_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_lines'))
    )
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_lines_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_lines_entry_id'), ['entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_lines_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_lines_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_journal_lines_entry_id'))
        batch_op.drop_index(batch_op.f('ix_journal_lines_account_id'))

    op.drop_table('journal_lines')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_entry_date'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_name'))
        batch_op.drop_index(batch_op.f('ix_accounts_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accounts_code'))
        batch_op.drop_index(batch_op.f('ix_accounts_account_type'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
