"""pharmacy and laboratory tables

Revision ID: 6fddaaedb633
Revises: 0aea3d9109b2
Create Date: 2026-07-18 22:58:41.753811
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6fddaaedb633'
down_revision: str | None = '0aea3d9109b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_tests',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('sample_type', sa.String(length=60), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_range', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name='fk_updated_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_tests'))
    )
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_tests_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_tests_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_tests_name'), ['name'], unique=False)

    op.create_table('medications',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('generic_name', sa.String(length=120), nullable=True),
    sa.Column('form', sa.String(length=40), nullable=True),
    sa.Column('strength', sa.String(length=60), nullable=True),
    sa.Column('barcode', sa.String(length=60), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name='fk_updated_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medications'))
    )
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medications_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_medications_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_medications_name'), ['name'], unique=False)

    op.create_table('lab_requests',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('lab_test_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('result_value', sa.String(length=120), nullable=True),
    sa.Column('result_flag', sa.String(length=20), nullable=True),
    sa.Column('result_notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lab_test_id'], ['lab_tests.id'], name=op.f('fk_lab_requests_lab_test_id_lab_tests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_lab_requests_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_lab_requests_requested_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name='fk_updated_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_requests'))
    )
    with op.batch_alter_table('lab_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_requests_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_requests_lab_test_id'), ['lab_test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_requests_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_requests_requested_by_id'), ['requested_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_requests_status'), ['status'], unique=False)

    op.create_table('stock_batches',
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=60), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name=op.f('fk_stock_batches_medication_id_medications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name='fk_updated_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_batches'))
    )
    with op.batch_alter_table('stock_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_batches_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_batches_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_batches_medication_id'), ['medication_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_batches_medication_id'))
        batch_op.drop_index(batch_op.f('ix_stock_batches_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_stock_batches_expiry_date'))

    op.drop_table('stock_batches')
    with op.batch_alter_table('lab_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_requests_status'))
        batch_op.drop_index(batch_op.f('ix_lab_requests_requested_by_id'))
        batch_op.drop_index(batch_op.f('ix_lab_requests_patient_id'))
        batch_op.drop_index(batch_op.f('ix_lab_requests_lab_test_id'))
        batch_op.drop_index(batch_op.f('ix_lab_requests_is_deleted'))

    op.drop_table('lab_requests')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medications_name'))
        batch_op.drop_index(batch_op.f('ix_medications_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_medications_barcode'))

    op.drop_table('medications')
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_tests_name'))
        batch_op.drop_index(batch_op.f('ix_lab_tests_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_lab_tests_code'))

    op.drop_table('lab_tests')
    # ### end Alembic commands ###
