"""Recovery from passwords typed with the wrong keyboard layout active.

The problem this solves
-----------------------
Afghan/Iranian clinic machines almost always have both a US (0409) and a
Persian (0429) Windows keyboard installed, toggled with Alt+Shift. When the
Persian layout is active the operator types ``Amin2026`` but the *password*
field — which is masked, so nothing looks wrong — actually receives
``َئهد2026``. Authentication then fails forever no matter how often the
password is reset, and each reset only produces another unenterable string.

Provenance of the tables
------------------------
These are **not** hand-copied from a reference. They were generated by asking
Windows itself: loading both layouts with ``LoadKeyboardLayoutW`` and probing
every virtual key, shifted and unshifted, through ``ToUnicodeEx``. Three
findings from that probe shape the code below:

* Every letter key differs between the layouts, so all 26 map cleanly.
* The **digit row is identical** under both layouts — digits were never the
  problem. Digit folding is kept anyway for text pasted from a Persian source.
* Two hazards, both handled explicitly:
  ``Shift+R`` emits the four-character Rial sign ``ريال`` (decomposing it would
  forge bogus single-char entries that collide with ``ر``/``ا``/``ل``), and
  ``Shift+I/O/P/U`` emit plain ASCII ``] [ \\ ,`` — remapping those would
  corrupt a *correctly* typed password. Only non-ASCII keys are ever remapped.

Policy
------
* **verify time** — a failed password is retried once through
  :func:`from_persian_layout`, so a layout slip is forgiven. This weakens
  nothing: it accepts an alternate *rendering of the same physical keystrokes*,
  not a different secret.
* **hash time** — a password being *set* is never silently remapped; the UI
  warns instead. Rewriting a secret the user deliberately chose would be worse
  than the bug.
"""
from __future__ import annotations

# Unshifted Persian (0429) -> US (0409) for the same physical key.
_UNSHIFTED: dict[str, str] = {
    "ش": "a", "ذ": "b", "ز": "c", "ی": "d", "ث": "e", "ب": "f",
    "ل": "g", "ا": "h", "ه": "i", "ت": "j", "ن": "k", "م": "l",
    "ئ": "m", "د": "n", "خ": "o", "ح": "p", "ض": "q", "ق": "r",
    "س": "s", "ف": "t", "ع": "u", "ر": "v", "ص": "w", "ط": "x",
    "غ": "y", "ظ": "z",
}

# Shifted Persian -> the capital the same key yields on US. ASCII-producing
# shifted keys (Shift+I/O/P/U -> ] [ \ ,) are deliberately EXCLUDED: they are
# indistinguishable from those characters typed on purpose.
_SHIFTED: dict[str, str] = {
    "َ": "A", "إ": "B", "ژ": "C", "ِ": "D", "ٍ": "E", "ّ": "F",
    "ۀ": "G", "آ": "H", "ـ": "J", "«": "K", "»": "L", "ء": "M",
    "أ": "N", "ً": "Q", "ُ": "S", "،": "T", "ؤ": "V", "ٌ": "W",
    "ي": "X", "؛": "Y", "ة": "Z",
}

# Keys whose Persian output is more than one character. Substituted as whole
# strings BEFORE per-character mapping, never decomposed.
_MULTI: dict[str, str] = {"ريال": "R"}

# Extended Arabic-Indic (Persian) U+06F0-U+06F9 and Arabic-Indic U+0660-U+0669.
_DIGITS: dict[str, str] = {
    chr(base + offset): str(offset)
    for base in (0x06F0, 0x0660)
    for offset in range(10)
}

# Every character that only a Persian layout can produce. ASCII is excluded by
# construction, so a correctly typed password never matches.
_PERSIAN_CHARS = frozenset({*_UNSHIFTED, *_SHIFTED, *_DIGITS})


def normalize_digits(text: str) -> str:
    """Fold Persian/Arabic-Indic digits to ASCII. Identity for ASCII input."""
    if not text:
        return text
    return "".join(_DIGITS.get(ch, ch) for ch in text)


def from_persian_layout(text: str) -> str:
    """Re-read ``text`` as the keystrokes it would have been on a US layout.

    ASCII characters are passed through untouched, so this is a no-op for a
    password that was typed correctly and is safe to apply to any string.
    """
    if not text:
        return text
    for persian, latin in _MULTI.items():       # whole-string keys first
        text = text.replace(persian, latin)
    out = []
    for ch in text:
        mapped = _UNSHIFTED.get(ch) or _SHIFTED.get(ch) or _DIGITS.get(ch)
        out.append(mapped if mapped else ch)
    return "".join(out)


def has_persian_layout_chars(text: str) -> bool:
    """True when ``text`` holds characters only a Persian layout produces.

    Drives the login screen's live "your keyboard is in Persian" warning — the
    entire point is to tell the operator *while they type*, because the masked
    field gives them no other clue that anything is wrong.
    """
    if not text:
        return False
    if any(ch in _PERSIAN_CHARS for ch in text):
        return True
    return any(part in text for part in _MULTI)


def looks_non_ascii(text: str) -> bool:
    """True when any character falls outside ASCII (a wider net than above)."""
    if not text:
        return False
    return any(ord(ch) > 127 for ch in text)
